AllCops:
  Include:
    - '**/*.rb'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.ru'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
  Exclude:
    - bin/*
    - db/schema.rb
    - node_modules/**/*
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Max: 39

Metrics/BlockLength:
  Exclude:
  - '**/*_spec.rb'
  - 'spec/factories*/*.rb'
  - 'config/routes.rb'
  ExcludedMethods: ['guard', 'included', 'class_eval']

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 9

Naming/MethodParameterName:
  MinNameLength: 2

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/NestedParenthesizedCalls:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%i': '()'
    '%r': '{}'
    '%w': '()'

Style/RescueModifier:
  Enabled: false
